# Site settings
title: John Dorian
description: The easy-to-use JavaScript framework for those who only want to write HTML and CSS
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
sass:
  load_paths:
    - _sass
    - node_modules
      
# Exclude from processing
exclude:
  - .git
  - .gitignores
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
